apiVersion: apps/v1
kind: Deployment
metadata:
  name: conv-temp-kube-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: conv-temp-kube
  template:
    metadata:
      labels:
         app: conv-temp-kube
    spec:
      containers:
        - name: conv-temp-kube
          image: rogeriop1990cv/conv-temp-kube:v1
          ports:
          - containerPort: 8080
